todolisttable.html:	todolist.png
	rm -rf todolist; python2.6 ../util/slice.py todolist.png todolist > todolisttable.html
leffecttable.html:	leffect.png 
	rm -rf leffect; python2.6 ../util/slice.py leffect.png leffect > leffecttable.html

